print ('Een duizendpoot miste in Loenen')
print ('bij het opstaan opeens al zijn schoenen.')
print ('Hij wist niet dat heel')
print ('het hotel personeel')
print ('er al urenlang op stond te boenen.')
